# Generated by Django 5.1.6 on 2025-02-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='job_title',
        ),
        migrations.CreateModel(
            name='ProfileCompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='companies',
            field=models.ManyToManyField(related_name='members', through='organization.ProfileCompanyRole', to='organization.company'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organization.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='profilecompanyrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.role'),
        ),
    ]
