# Generated by Django 5.1.6 on 2025-02-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_itemdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Inventory',
            new_name='inventory',
        ),
    ]
