# Generated by Django 5.1.6 on 2025-02-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_inventory_item_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetail',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('url', 'URL'), ('bool', 'Boolean')], default='text', max_length=10),
        ),
    ]
