# Generated by Django 5.1.6 on 2025-02-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_itemdetail_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemdetail',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='itemdetail',
            name='type',
        ),
        migrations.CreateModel(
            name='InventorySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('url', 'URL'), ('bool', 'Boolean')], default='text', max_length=10)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='inventory.inventory')),
            ],
            options={
                'unique_together': {('inventory', 'key')},
            },
        ),
    ]
